### ISSUE TITLE
Camera in W1L1 can pass through geometry, unlike Playground camera

### ISSUE THREAD

**Issue by amhartman** [ToasterBiome/Super-Mango-64#12]
Example from W1L1
![image](https://user-images.githubusercontent.com/57197911/115896431-6c265d00-a429-11eb-87cd-acd21a542490.png)
Playground Example
![image](https://user-images.githubusercontent.com/57197911/115896840-d4753e80-a429-11eb-9d20-fc97ad91fe16.png)

**Comment by ToasterBiome** [comment]
Fixed as of https://github.com/ToasterBiome/Super-Mango-64/commit/81fcbaa570bc24ec82ef4422752bdb508e9c212b
