### ISSUE TITLE
Rocks on the sandy ramp are underwhelming, need a system to manage/respawn them where they will go down the hill.

### ISSUE THREAD

**Issue by ToasterBiome** [ToasterBiome/Super-Mango-64#15]
Maybe if you get bonked by them you get hurt

**Comment by ToasterBiome** [comment]
The sandy ramp needs to be redone so that the boulders will roll off the level and then respawn. Also there needs to be a "cave" with some black texture that the bounders can pop out of.

**Comment by amhartman** [comment]
Ramp changed to jumping puzzle
