### ISSUE TITLE
W1L1: Sand Ramp has acts like stairs. 

### ISSUE THREAD

**Issue by mahrens1** [ToasterBiome/Super-Mango-64#19]
### Steps To Repeat:

1. Make your way through the first tier and over to the sand ramp.
2. Go up the sand ramp.

### Results
Player hits an invisible step while trying to walk up the ramp.

### Expected Results
Player should be able to walk up the ramp.

**Comment by ToasterBiome** [comment]
#8 code issue

**Comment by amhartman** [comment]
Fixed
