### ISSUE TITLE
Mango acts as if falling/in air when jumping on the edge of objects

### ISSUE THREAD

**Issue by amhartman** [ToasterBiome/Super-Mango-64#35]
Mango can jump onto rocks and trees and stick there and look as if falling,
Mango also looks as if falling if on the edge of platform geometry such as logs and lily pads

**Comment by ToasterBiome** [comment]
fixed(ish!) https://github.com/ToasterBiome/Super-Mango-64/commit/c21e969b55dac599b29f50a519a19cb7e14c2184
