### ISSUE TITLE
Mango's slope limit being reduced from 45 to 15 makes it so he clips on the sandy ramp, also not updated in prefab

### ISSUE THREAD

**Issue by ToasterBiome** [ToasterBiome/Super-Mango-64#8]
Probably something to do with attempting to fix #7 

![Unity_RbGRTM6doH](https://user-images.githubusercontent.com/5091394/115895227-cae6d900-a41f-11eb-9fb6-c5a61de6ac96.png)

**Comment by amhartman** [comment]
Fixed
